### ISSUE TITLE
FileSizes uses 1000 as factor, not 1024

### ISSUE THREAD

**Issue by okrische** [JangoBrick/angular-filesize-filter#2]
I have the following file size in bytes: 16385745374

I would expect, that these values are converted like this:

- 16001704.46 kb
- 15626.66 MB 
- 15.26 GB

Maybe i am a bit too old fashioned to use 1024 as a factor instead of 1000 as this filter does, but i would assume, my version is the correct one.

What would you say? Or was this done on purpose?

**Comment by meyfa** [comment]
Although this question has been the center of many debates over the past few decades, the consensus now seems to be that a "kilobyte" is 1000 bytes (compare kilogram, which is 1000 grams, or kilometer, which is 1000 meters). When using 1024, the correct term is [kibibyte](https://en.wikipedia.org/wiki/Kibibyte) (e.g. 16001704.46 KiB). Higher units are mebibyte, gibibyte, and so forth.

Therefore, I would argue that the filter's output is correct. Nonetheless, I can see that in some cases using the other set of units, or even going against the convention might be advantageous. I might take a look at adding this as an option tomorrow, and will keep you posted.

Thanks for opening this issue!

**Comment by okrische** [comment]
Nono, just close this one, i totally agree with you. Many tools in my world still use binary, so i did not even think about it, that others might have moved on with "decimal" for like "MB" already.

But adding kibi (KiB), mebi (MiB) and so on, i would not mind to have these in a different modus. :-)

**Comment by meyfa** [comment]
Alright, closing this. :-)
